language: java
jdk:
  - oraclejdk8
 
notifications:
  email:
    recipients:
      - dev@meltzow.net

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

script: ./gradlew clean build

